boostrap

diff --git a/overlays/pkgs/nixos-cli/nixos b/overlays/pkgs/nixos-cli/nixos
--- a/overlays/pkgs/nixos-cli/nixos
+++ b/overlays/pkgs/nixos-cli/nixos
@@ -286,7 +286,7 @@ nixos_bootstrap_usage() {
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  nixos bootstrap TYPE [OPTIONS]\n"
+  printf "  nixos bootstrap TYPE [CONFIGURATION] [OPTIONS]\n"
   printf "  nixos bootstrap --help | -h\n"
   echo
 
@@ -313,11 +313,17 @@ nixos_bootstrap_usage() {
     printf "    uefi, bios, linode\n"
     echo
 
+    # :argument.usage
+    printf "  %s\n" "$(blue "CONFIGURATION")"
+    printf "    Name of configuration\n"
+    echo
+
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples:")"
     printf "  nixos bootstrap linode\n"
     printf "  nixos bootstrap uefi --swap min\n"
     printf "  nixos bootstrap bios --swap 8\n"
+    printf "  nixos bootstrap switch sol\n"
     echo
 
   fi
@@ -823,8 +829,8 @@ nixos_linode_command() {
     # Test login
     info "Opening a Weblish console:"
     url "https://cloud.linode.com/linodes/$id/lish/weblish" && echo
-    info "Login as user, pull from git, and rebuild config (copied to clipboard):"
-    line1="cd /etc/nixos; git pull"
+    info "Login as root, pull from git, and rebuild config (copied to clipboard):"
+    line1="cd /etc/nixos; git pull; "
     line2="sudo nixos-rebuild switch"
     echo $line1
     echo $line2
@@ -873,6 +879,9 @@ nixos_bootstrap_command() {
 
     # Be prepared
     install_dependencies
+
+    # Switch configuration (stage 2)
+    is_switch && switch_configuration
 
     # Banner
     yellow "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
@@ -1048,21 +1057,9 @@ nixos_bootstrap_command() {
   }
 
   function install_dependencies {
-    if hasnt parted; then
-      info "Installing parted"
-      task nix-env -iA nixos.parted
-    fi
     if hasnt git; then
       info "Installing git"
       task nix-env -iA nixos.git
-    fi
-    if hasnt awk; then
-      info "Installing awk"
-      task nix-env -iA nixos.gawk
-    fi
-    if hasnt sed; then
-      info "Installing sed"
-      task nix-env -iA nixos.gnused
     fi
     if hasnt fzf; then
       info "Installing fzf"
@@ -1070,8 +1067,40 @@ nixos_bootstrap_command() {
     fi
   }
 
+  # Pull in rekeyed secrets, copy hardware-configuration from min to host, and switch
+  function switch_configuration {
+    local host="${args[configuration]}"
+    if has_configuration; then
+
+      info "Pulling secrets"
+      task "cd /etc/nixos; git pull" && echo
+
+      info "Copying generated hardware-configuration to $host"
+      task mv -f /etc/nixos/configurations/min/hardware-configuration.nix /etc/nixos/configurations/$host/hardware-configuration.nix
+      task "cd /etc/nixos; git restore configurations/min" && echo
+
+      info "Rebuilding system to $host"
+      task -d "nixos-rebuild switch --flake /etc/nixos\#${args[configuration]}"
+      nixos-rebuild switch --flake /etc/nixos\#${args[configuration]}
+
+      info "Rebuild complete!"
+      info "Reboot to ensure everything worked. Commit the generated hardware-configuration.nix and git push to the repo."
+
+    else
+      warn "Exiting, missing configuration"
+      return 1
+    fi
+  }
+
+  function is_switch {
+    [ "${args[type]}" = "switch" ] && return 0 || return 1
+  }
+
+  function has_configuration {
+    [ "${args[configuration]}" != "" ] && return 0 || return 1
+  }
+
   function is_linode {
-    # [ "$ARG" = "LINODE" ] && return 0 || return 1
     [ "${args[type]}" = "linode" ] && return 0 || return 1
   }
 
@@ -1603,6 +1632,10 @@ nixos_bootstrap_parse_requirements() {
 
           args['type']=$1
           shift
+        elif [[ -z ${args['configuration']+x} ]]; then
+
+          args['configuration']=$1
+          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -1615,7 +1648,7 @@ nixos_bootstrap_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['type']+x} ]]; then
-    printf "missing required argument: TYPE\nusage: nixos bootstrap TYPE [OPTIONS]\n" >&2
+    printf "missing required argument: TYPE\nusage: nixos bootstrap TYPE [CONFIGURATION] [OPTIONS]\n" >&2
     exit 1
   fi
 
