bashly

diff --git a/overlays/pkgs/nixos-cli/nixos b/overlays/pkgs/nixos-cli/nixos
--- a/overlays/pkgs/nixos-cli/nixos
+++ b/overlays/pkgs/nixos-cli/nixos
@@ -34,6 +34,7 @@ nixos_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
+  printf "  %s   Wizard up a NixOS installation\n" "$(green "wizard")         "
   printf "  %s   Shortcut for nixos-rebuild switch\n" "$(green "switch")         "
   printf "  %s   Edit or add secrets to secrets/files\n" "$(green "secrets")        "
   printf "  %s   Rekey secrets with secrets/keys\n" "$(green "rekey")          "
@@ -54,6 +55,52 @@ nixos_usage() {
     echo
     printf "  %s\n" "$(magenta "--version, -v")"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+nixos_wizard_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "nixos wizard - Wizard up a NixOS installation\n"
+    echo
+
+  else
+    printf "nixos wizard - Wizard up a NixOS installation\n"
+    echo
+
+  fi
+
+  printf "Alias: w\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  nixos wizard [TYPE] [OPTIONS]\n"
+  printf "  nixos wizard --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--swap, -s SWAP")"
+    printf "    min, max, or any number of GB for swap (default: max)\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "TYPE")"
+    printf "    uefi, bios, linode\n"
     echo
 
   fi
@@ -475,28 +522,28 @@ cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
 # True if command or file does exist
 function has {
-  if [ -e "$1" ]; then return 0; fi
+  if [[ -e "$1" ]]; then return 0; fi
   command -v "$1" >/dev/null 2>&1 && { return 0; }
   return 1
 }
 
 # True if command or file doesn't exist
 function hasnt {
-  if [ -e "$1" ]; then return 1; fi
+  if [[ -e "$1" ]]; then return 1; fi
   command -v "$1" >/dev/null 2>&1 && { return 1; }
   return 0
 }
 
 # True if variable is not empty
 function defined {
-  if [ -z "$1" ]; then return 1; fi
+  if [[ -z "$1" ]]; then return 1; fi
 
   return 0
 }
 
 # True if variable is empty
 function empty {
-  if [ -z "$1" ]; then return 0; fi
+  if [[ -z "$1" ]]; then return 0; fi
   return 1
 }
 
@@ -517,13 +564,9 @@ function warn {
 # Echo task and execute command (unless --dry-run)
 function task {
 
-  local cmd x
-  case "$1" in
-    "--dry-run" | "-d" ) cmd="${*:2}" ;;
-    *                  ) cmd="${*}"; x=1 ;;
-  esac
+  local cmd="$(strip_flags "${@}")"
   echo "$(magenta_bold ">") $(magenta "$cmd")";
-  [ -z "$x" ] || eval "$cmd" > /tmp/task
+  is_dry "${@}" || eval "$cmd" > /tmp/task
 }
 
 # Echo URL, copy to clipboard, and open in browser
@@ -536,30 +579,25 @@ function url {
 
 # Pause script until input
 function pause {
-  echo -n "$(green_bold "#") $(green "Press") $(blue_bold "y") $(green "to continue:") "
-
-  local continue=""
-  while [[ "$continue" != "y" ]]; do
-
-    read -n 1 continue;
-
-  done
-  echo
+  info "${1-Paused}"
+  smenu -d -i continue -a e:7 i:2,br c:2,blr <<< "Press enter to continue ..."
 }
 
-# Ask confirmation, return true if [y], return false if anything else
+function is_warn {
+  [[ "$1" == "--warn" || "$1" == "-w" ]] && return 0
+  return 1
+}
 
-function ask {
+function is_dry {
+  [[ "$1" == "--dry-run" || "$1" == "-d" ]] && return 0
+  return 1
+}
 
+function strip_flags {
   case "$1" in
-    "--warn" | "-w" ) echo -n "$(red_bold "#") $(red "${*:2}")" ;;
-    "--info" | "-i" ) echo -n "$(green_bold "#") $(green "${*:2}")" ;;
-    *               ) echo -n "$(green_bold "#") $(green "${*}")" ;;
+    "--warn" | "-w" | "--info" | "-i" | "--dry-run" | "-d") echo "${*:2}" ;;
+    * ) echo "${*}" ;;
   esac
-  read -p " $(blue_bold y)/[$(red_bold n)] " -n 1 -r
-  echo && [[ $REPLY =~ ^[Yy]$ ]]
-  [ ! $? -ne 0 ] && return 0 || return 1
-
 }
 
 # Echo but spaces replaced with newlines
@@ -567,13 +605,75 @@ function explode {
   echo "$@" | tr ' ' '\n'
 }
 
-# Styled fzf with label argument
-function pick {
-  local label
-  [ -z "$1" ] || label=" $(green_bold "${*}") "
+# if confirm --warn "Wanna go on?"; then
+#   echo "You do! :)"
+# else
+#   echo "You don't :("
+# fi
+function confirm {
+  local out="$(strip_flags "${@}")"
+  [[ -z "$out" ]] && out="Confirm?"
+  is_warn "${@}" && warn "$out" || info "$out"
+  [[ "$(ask "yes no")" == "yes" ]] && return 0 || return 1
 
-  has fzf && fzf --border-label="$label" --border --height=30% --margin=1 --padding=1 --layout=reverse --info=hidden
 }
+
+# info "Which color?"
+# color="$(ask red green blue)"
+# info "What is your name?"
+# name="$(ask)"
+function ask {
+
+  # Check for args or stdin
+  local choices="${@}"
+  [[ -p /dev/stdin ]] && choices="$(cat -)"
+  # If any choices, get choice from smenu
+  if [[ -n "$choices" ]]; then
+    smenu -a i:3,b c:3,br <<< "$choices"
+  # Otherwise, prompt for input
+  else
+    local reply=""; while [[ -z "$reply" ]]; do
+      read -p "$(blue_bold :) " -e reply
+    done; echo "$reply"
+  fi
+}
+
+function ask_disk {
+  smenu -c -q -n 20 -N -d \
+    -I '/__/ /g' -E '/__/ /g' \
+    -i ^nvme -i ^sd -i ^hd -i ^vd \
+    -i refresh -i cancel \
+    -a e:4 i:6,b c:6,br  \
+    -1 '(refresh|cancel)' '3,b' \
+    -s /refresh \
+    <<-EOF
+			$(lsblk -o NAME,FSTYPE,LABEL,FSAVAIL,FSUSE%,MOUNTPOINT)
+			__
+			refresh__ cancel__
+		EOF
+}
+
+# smenu formatting
+# ----------------
+#
+# [fb]/[bg],[blru]
+#
+# 0: black    1: red    2: green
+# 3: yellow   4: blue   5: purple
+# 6: aqua     7: white  8: gray
+#
+
+# [b]old b[l]inking [r]everse [u]nderline
+#
+# -N                   :: numbers added for selection
+# -q                   :: hide scroll bar
+# -N                   :: numbers added for selection
+# -n 20                :: number of lines height
+# -i '^[a-z].'         :: regex for what is selectable
+# -1 '^[a-z].' '1/0,b' :: regex for formatting
+# -m                   :: Message for title
+# -d                   :: Clear menu after selection
+# -W$'\n'              ::
 
 # src/lib/send_completions.sh
 send_completions() {
@@ -643,6 +743,16 @@ send_completions() {
 }
 
 # :command.command_functions
+# :command.function
+nixos_wizard_command() {
+  # src/wizard_command.sh
+  echo "# this file is located in 'src/wizard_command.sh'"
+  echo "# code for 'nixos wizard' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+}
+
 # :command.function
 nixos_switch_command() {
   # src/switch_command.sh
@@ -1215,6 +1325,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    wizard | w)
+      action="wizard"
+      shift
+      nixos_wizard_parse_requirements "$@"
+      shift $#
+      ;;
+
     switch | sw)
       action="switch"
       shift
@@ -1304,6 +1421,70 @@ parse_requirements() {
         # :command.parse_requirements_case_simple
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+nixos_wizard_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        nixos_wizard_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="wizard"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --swap | -s)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--swap']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--swap requires an argument: --swap, -s SWAP" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['type']+x} ]]; then
+
+          args['type']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
@@ -1763,6 +1944,15 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "wizard")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        nixos_wizard_usage
+      else
+        nixos_wizard_command
+      fi
+      ;;
+
     "switch")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
