nixos-cli

diff --git a/overlays/pkgs/nixos-cli/nixos b/overlays/pkgs/nixos-cli/nixos
--- a/overlays/pkgs/nixos-cli/nixos
+++ b/overlays/pkgs/nixos-cli/nixos
@@ -210,7 +210,7 @@ nixos_rekey_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(magenta "--force, -f FORCE")"
+    printf "  %s\n" "$(magenta "--force, -f")"
     printf "    Force rekey\n"
     echo
 
@@ -824,7 +824,7 @@ nixos_switch_command() {
 # :command.function
 nixos_secrets_command() {
   # src/secrets_command.sh
-  #!/usr/bin/env bash
+  # inspect_args
   local dir="/etc/nixos/secrets" secret
 
   function main {
@@ -927,20 +927,205 @@ nixos_secrets_command() {
 # :command.function
 nixos_rekey_command() {
   # src/rekey_command.sh
-  echo "# this file is located in 'src/rekey_command.sh'"
-  echo "# code for 'nixos rekey' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  # inspect_args
+  local dir="/etc/nixos/secrets" force
+
+  function main {
+
+    # Ensure agenix
+    has agenix || error "agenix missing"
+    force="${args[--force]}"
+
+    # Update keys/default.nix
+    write_nix
+
+    # Rekey secrets with agenix and restage on git
+    show $force
+    if [[ "$(prev_hash)" != "$(calc_hash)" ]] || [[ "$force" == "1" ]]; then
+      agenix_rekey && update_hash && git_commit
+    else
+      info "No changes detected"
+    fi
+
+  }
+
+  # Write the default.nix file compiling all public keys
+  function write_nix {
+
+    # Ouput file path
+
+    local nix="$dir/keys/default.nix"
+
+    # List of all key names
+    local users=""
+    local systems=""
+
+    info "Writing $nix"
+
+    # Build recursive attribute set
+    echo "$(prev_hash)" > $nix
+    echo "# Do not modify this file!  It was generated by ‘nixos rekey’ "  >> $nix
+    echo "# and may be overwritten by future invocations. "                >> $nix
+    echo "# Please add public keys to $dir/keys/*.pub "                    >> $nix
+    echo "rec {"                                                           >> $nix
+    echo ""                                                                >> $nix
+
+    # Read each @*.pub file (users) in the directory
+    for file in $dir/keys/@*.pub; do
+
+      # Derive the attribute key from the filename
+      local key=$(basename "$file" ".pub")
+      key="${key#@}" # remove @ from start
+
+      # Write the attribute key and value to default.nix
+      echo "  users.$key = \"$(cat "$file")\";" >> $nix
+
+      # Collect list of key names
+      users=$(echo " $users users.$key " | xargs)
+
+    done
+
+    # Finish with users, containing list of key names
+    echo "  users.all = [ $users ];" >> $nix
+
+    echo "" >> $nix
+
+    # Read each *.pub file in the directory
+    for file in $dir/keys/*.pub; do
+
+      [[ "$file" =~ ^$dir/keys/@.* ]] && continue
+
+      # Derive the attribute key from the filename
+      local key=$(basename "$file" ".pub")
+
+      # Write the attribute key and value to default.nix
+      echo "  systems.$key = \"$(cat "$file")\";" >> $nix
+
+      # Collect list of key names
+      systems=$(echo " $systems systems.$key " | xargs)
+
+    done
+
+    # Finish with systems, containing list of key names
+    echo "  systems.all = [ $systems ];" >> $nix
+
+    echo "" >> $nix
+
+    # Finish with all, containing list of key names
+    echo "  all = users.all ++ systems.all;" >> $nix
+
+    echo ""  >> $nix
+    echo "}" >> $nix
+
+    show "echo \"rec { ... }\" > $nix"
+
+  }
+
+  function prev_hash {
+    head -n1 $dir/keys/default.nix
+  }
+
+  function calc_hash {
+    echo "# $(ls -lah $dir/keys/*.pub | md5sum | awk '{print $1}')"
+  }
+
+  function update_hash {
+    local file="$dir/keys/default.nix"
+    local hash="$(calc_hash)"
+    sed -i "1s/.*/$hash/" $file
+  }
+
+  # Rekey secrets with agenix
+  function agenix_rekey {
+
+    # Rekey and add any new secrets
+    info "Rekeying secrets with agenix"
+
+    show "cd $dir/secrets && agenix --rekey"
+    cd $dir && agenix --rekey && return 0
+    return 1
+
+  }
+
+  function git_commit {
+    task "cd $dir && git add . && git commit -m rekey"
+  }
+
+  main
 
 }
 
 # :command.function
 nixos_keyscan_command() {
   # src/keyscan_command.sh
-  echo "# this file is located in 'src/keyscan_command.sh'"
-  echo "# code for 'nixos keyscan' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  # inspect_args
+  local dir="/etc/nixos/secrets" ip hostname force filename key
+
+  function main {
+
+    # Ensure ssh-keyscan
+    has ssh-keyscan || error "ssh-keyscan missing"
+
+    # Set up args
+    force="${args[--force]}"
+    ip="${args[host]}"
+    hostname="${args[name]}"
+    [[ -z "$hostname" ]] && hostname="$ip"
+
+    # Modify hostname to ensure
+
+    # - it doesn't end in .pub
+    # - periods replaces with hypens
+    # - only alphanumeric with hypens and underscores
+    # - no leading/trailing hypens and underscores
+    hostname="$(awk '{
+
+      gsub(/\.pub$/, "", $0);
+
+      gsub(/[\. -]+/, "-", $0);
+
+      gsub(/[^a-zA-Z0-9_-]+/, "", $0);
+
+      gsub(/^[-_]+|[-_]+$/, "", $0);
+
+      print tolower($0)
+
+    }' <<< $hostname)"
+
+    # Attempt to scan public key
+    task ssh-keyscan -t ssh-ed25519 $ip 2> /dev/null
+    key="$(last | awk '{print $2} {print $3}' | xargs)"
+    filename="${dir}/keys/${hostname}.pub"
+
+    show "key=\"$key\""
+    if [[ -z "$key" ]]; then
+      error "failed to scan key from $ip"
+    fi
+
+    # Ask to delete existing key
+    if [[ "$force" == "1" ]]; then
+      task "rm -f $filename"
+    fi
+
+    if [[ -e $filename ]]; then
+      if ask "Overwrite existing \"$hostname\" key?"; then
+        task "rm -f $filename"
+      else
+        error "$hostname already exists in keys directory"
+      fi
+    fi
+
+    # Write key to file
+    show "echo \"\$key\" > $filename"
+    echo "$key" > $filename
+    info "Success: $name written to $filename"
+
+    # Rekey the secrets with the new identity
+    nixos rekey
+
+  }
+
+  main
 
 }
 
@@ -1768,16 +1953,9 @@ nixos_rekey_parse_requirements() {
       # :flag.case
       --force | -f)
 
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          args['--force']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--force requires an argument: --force, -f FORCE" >&2
-          exit 1
-        fi
+        # :flag.case_no_arg
+        args['--force']=1
+        shift
         ;;
 
       -?*)
