cachix

diff --git a/overlays/pkgs/nixos-cli/nixos b/overlays/pkgs/nixos-cli/nixos
--- a/overlays/pkgs/nixos-cli/nixos
+++ b/overlays/pkgs/nixos-cli/nixos
@@ -36,6 +36,7 @@ nixos_usage() {
   printf "%s\n" "$(bold "Commands:")"
   printf "  %s   Bootstrap a NixOS installation\n" "$(green "bootstrap")      "
   printf "  %s   Shortcut for nixos-rebuild switch\n" "$(green "switch")         "
+  printf "  %s   Shortcut for nix build piped to cachix\n" "$(green "cache")          "
   echo
   printf "%s\n" "$(bold "Secrets Commands:")"
   printf "  %s   Edit or add secrets to secrets/files\n" "$(green "secrets")        "
@@ -141,6 +142,38 @@ nixos_switch_usage() {
   printf "%s\n" "$(bold "Usage:")"
   printf "  nixos switch\n"
   printf "  nixos switch --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+nixos_cache_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "nixos cache - Shortcut for nix build piped to cachix\n"
+    echo
+
+  else
+    printf "nixos cache - Shortcut for nix build piped to cachix\n"
+    echo
+
+  fi
+
+  printf "Alias: c\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  nixos cache\n"
+  printf "  nixos cache --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1376,6 +1409,14 @@ nixos_switch_command() {
 }
 
 # :command.function
+nixos_cache_command() {
+  # src/cache_command.sh
+  show "nix build .#nixosConfigurations.$(hostname).config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push suderman"
+  nix build .#nixosConfigurations.$(hostname).config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push suderman
+
+}
+
+# :command.function
 nixos_secrets_command() {
   # src/secrets_command.sh
   include awk:gawk git sed:gnused
@@ -1806,6 +1847,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    cache | c)
+      action="cache"
+      shift
+      nixos_cache_parse_requirements "$@"
+      shift $#
+      ;;
+
     secrets | s)
       action="secrets"
       shift
@@ -2005,6 +2053,50 @@ nixos_switch_parse_requirements() {
 
   # :command.command_filter
   action="switch"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+nixos_cache_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        nixos_cache_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="cache"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2350,6 +2442,15 @@ run() {
         nixos_switch_usage
       else
         nixos_switch_command
+      fi
+      ;;
+
+    "cache")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        nixos_cache_usage
+      else
+        nixos_cache_command
       fi
       ;;
 
