save

diff --git a/overlays/pkgs/nixos-cli/nixos b/overlays/pkgs/nixos-cli/nixos
--- a/overlays/pkgs/nixos-cli/nixos
+++ b/overlays/pkgs/nixos-cli/nixos
@@ -154,13 +154,19 @@ nixos_secrets_usage() {
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  nixos secrets [SECRET]\n"
+  printf "  nixos secrets [SECRET] [OPTIONS]\n"
   printf "  nixos secrets --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--commit, -c")"
+    printf "    Automatically commit changes to git\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -211,7 +217,12 @@ nixos_rekey_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--force, -f")"
-    printf "    Force rekey\n"
+    printf "    Force rekey even if no changes have been detected\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--commit, -c")"
+    printf "    Automatically commit changes to git\n"
     echo
 
     # :command.usage_fixed_flags
@@ -223,6 +234,7 @@ nixos_rekey_usage() {
     printf "%s\n" "$(bold "Examples:")"
     printf "  nixos rekey\n"
     printf "  nixos rekey --force\n"
+    printf "  nixos rekey --commit\n"
     echo
 
   fi
@@ -244,7 +256,7 @@ nixos_keyscan_usage() {
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  nixos keyscan HOST [NAME] [OPTIONS]\n"
+  printf "  nixos keyscan IP [HOSTNAME] [OPTIONS]\n"
   printf "  nixos keyscan --help | -h\n"
   echo
 
@@ -258,6 +270,11 @@ nixos_keyscan_usage() {
     printf "    Force rekey after keyscan\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--commit, -c")"
+    printf "    Automatically commit changes to git\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -267,12 +284,12 @@ nixos_keyscan_usage() {
     printf "%s\n" "$(bold "Arguments:")"
 
     # :argument.usage
-    printf "  %s\n" "$(blue "HOST")"
+    printf "  %s\n" "$(blue "IP")"
     printf "    IP address or hostname\n"
     echo
 
     # :argument.usage
-    printf "  %s\n" "$(blue "NAME")"
+    printf "  %s\n" "$(blue "HOSTNAME")"
     printf "    Name of host (default: first argument)\n"
     echo
 
@@ -835,7 +852,7 @@ nixos_secrets_command() {
 
   function main {
 
-    # Get secret arg and ensure agenix
+    # Get args and ensure agenix
     secret="${args[secret]}"
     has agenix || error "agenix missing"
 
@@ -856,8 +873,8 @@ nixos_secrets_command() {
     # Edit secret with agenix
     cd $dir && agenix --edit "files/$secret.age"
 
-    # Update age/default.nix
-    write_nix
+    # Update files/default.nix
+    write_files_nix
 
     # Commit secrets
     git_commit
@@ -865,7 +882,7 @@ nixos_secrets_command() {
   }
 
   # Write the default.nix file compiling all age files
-  function write_nix {
+  function write_files_nix {
 
     # Ouput file path
 
@@ -874,11 +891,11 @@ nixos_secrets_command() {
     info "Writing $nix"
 
     # Build recursive attribute set
-    echo "# Do not modify this file!  It was generated by ‘secrets’ " > $nix
-    echo "# and may be overwritten by future invocations. "          >> $nix
-    echo "# Please add age files to $dir/files/*.age "               >> $nix
-    echo "{"                                                         >> $nix
-    echo ""                                                          >> $nix
+    echo "# Do not modify this file!  It was generated by ‘nixos secrets’ " > $nix
+    echo "# and may be overwritten by future invocations. "                >> $nix
+    echo "# Please add age files to $dir/files/*.age "                     >> $nix
+    echo "{"                                                               >> $nix
+    echo ""                                                                >> $nix
 
     # Read each encrypted age file
     for file in $dir/files/*.age; do
@@ -916,6 +933,7 @@ nixos_secrets_command() {
   function add_secret {
     [[ -z "$1" ]] && { return 1; }
     local nix="$dir/secrets.nix"
+    info "Appending $nix"
     task "sed -i '$ d' ${nix}"
     task "echo '  \"files/$1.age\".publicKeys = all;' >> $nix"
     task "echo '' >> $nix"
@@ -923,7 +941,15 @@ nixos_secrets_command() {
   }
 
   function git_commit {
-    task "cd $dir && git add . && git commit -m \"secret: $secret\""
+    info "Adding files to the staging area"
+    task "cd $dir"\
+         '&& git add ./secrets.nix ./files/*.age ./files/default.nix'
+    if [[ "${args[--commit]}" == "1" ]]; then
+      info "Committing staged files to the repository"
+      task "cd $dir"\
+           '&& git commit ./secrets.nix ./files/*.age ./files/default.nix'\
+           "-m 'secret: $secret'"
+    fi
   }
 
   main
@@ -934,19 +960,18 @@ nixos_secrets_command() {
 nixos_rekey_command() {
   # src/rekey_command.sh
   # inspect_args
-  local dir="/etc/nixos/secrets" force
+  local dir="/etc/nixos/secrets"
 
   function main {
 
     # Ensure agenix
     has agenix || error "agenix missing"
-    force="${args[--force]}"
 
     # Update keys/default.nix
-    write_nix
+    write_keys_nix
 
     # Rekey secrets with agenix and restage on git
-    if [[ "$(prev_hash)" != "$(calc_hash)" ]] || [[ "$force" == "1" ]]; then
+    if [[ "$(prev_hash)" != "$(calc_hash)" ]] || [[ "${args[--force]}" == "1" ]]; then
       agenix_rekey && update_hash && git_commit
     else
       info "No changes detected"
@@ -955,7 +980,7 @@ nixos_rekey_command() {
   }
 
   # Write the default.nix file compiling all public keys
-  function write_nix {
+  function write_keys_nix {
 
     # Ouput file path
 
@@ -1053,7 +1078,14 @@ nixos_rekey_command() {
   }
 
   function git_commit {
-    task "cd $dir && git add . && git commit -m rekey"
+    info "Adding files to the staging area"
+    task "cd $dir"\
+         '&& git add ./keys/*.pub ./keys/default.nix ./files/*.age'
+    if [[ "${args[--commit]}" == "1" ]]; then
+      info "Committing staged files to the repository"
+      task "cd $dir"\
+           '&& git commit ./keys/*.pub ./keys/default.nix ./files/*.age -m rekey'
+    fi
   }
 
   main
@@ -1073,8 +1105,8 @@ nixos_keyscan_command() {
 
     # Set up args
     force="${args[--force]}"
-    ip="${args[host]}"
-    hostname="${args[name]}"
+    ip="${args[ip]}"
+    hostname="${args[hostname]}"
     [[ -z "$hostname" ]] && hostname="$ip"
 
     # Modify hostname to ensure
@@ -1901,6 +1933,13 @@ nixos_secrets_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --commit | -c)
+
+        # :flag.case_no_arg
+        args['--commit']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -1959,6 +1998,14 @@ nixos_rekey_parse_requirements() {
         shift
         ;;
 
+      # :flag.case
+      --commit | -c)
+
+        # :flag.case_no_arg
+        args['--commit']=1
+        shift
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -2010,6 +2057,14 @@ nixos_keyscan_parse_requirements() {
         shift
         ;;
 
+      # :flag.case
+      --commit | -c)
+
+        # :flag.case_no_arg
+        args['--commit']=1
+        shift
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -2018,13 +2073,13 @@ nixos_keyscan_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        if [[ -z ${args['host']+x} ]]; then
+        if [[ -z ${args['ip']+x} ]]; then
 
-          args['host']=$1
+          args['ip']=$1
           shift
-        elif [[ -z ${args['name']+x} ]]; then
+        elif [[ -z ${args['hostname']+x} ]]; then
 
-          args['name']=$1
+          args['hostname']=$1
           shift
         else
           printf "invalid argument: %s\n" "$key" >&2
@@ -2037,8 +2092,8 @@ nixos_keyscan_parse_requirements() {
   done
 
   # :command.required_args_filter
-  if [[ -z ${args['host']+x} ]]; then
-    printf "missing required argument: HOST\nusage: nixos keyscan HOST [NAME] [OPTIONS]\n" >&2
+  if [[ -z ${args['ip']+x} ]]; then
+    printf "missing required argument: IP\nusage: nixos keyscan IP [HOSTNAME] [OPTIONS]\n" >&2
     exit 1
   fi
 
